import "../../globals.css";
import AdminHeader from "./components/AdminHeader";
import MenuHeader from "./components/MenuHeader";


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function AdminLayout({ children }) {
  return (
    <html lang="en">
      <body className="bg-gray-900">
        <AdminHeader/>
        <MenuHeader/>
        <div className="px-[10%] py-5">{children}</div>
      </body>
    </html>
  );
}
